[project]
name = "ragas-test"
version = "0.1.0"
description = "RAG-based evaluation dashboard"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ragas",
    "datasets",
    "langchain-google-genai",
    "python-dotenv",
    "streamlit>=1.28.0",
    "pandas>=2.0.0",
    "plotly>=5.15.0",
    "numpy>=1.24.0",
    "uv"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[tool.pytest.ini_options]
pythonpath = "."
