name: Dependency Review

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate
        allow-licenses: Apache-2.0, MIT, BSD-2-Clause, BSD-3-Clause, ISC
        deny-licenses: GPL-2.0, GPL-3.0, AGPL-1.0, AGPL-3.0

    - name: UV Lock Check
      run: |
        # Install UV
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source $HOME/.local/bin/env
        
        # Check if lock file is up to date
        uv lock --check
        
        # Check for security vulnerabilities in dependencies
        uv tree | grep -i "vulnerability\|security\|cve" || true