[global]
# 개발 모드 설정
developmentMode = false

[server]
# 서버 설정
port = 8503
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

# 성능 최적화
maxUploadSize = 200
maxMessageSize = 200

[browser]
# 브라우저 자동 열기 설정
gatherUsageStats = false

[runner]
# 실행 설정
magicEnabled = true

[logger]
# 로그 설정
level = "error"

[client]
# 클라이언트 설정
showErrorDetails = false

[theme]
# 테마 설정
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 